### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by bcomnes** [davidmarkclements/brittle#1]
Looks great!
A couple questions:

- Any plans to include a cli test runner?
- Any plans to have a default glob that discovers `*.test.js` or `*.spec.js` tests throughout a project?
- Any plans for built in coverage reporting? 

Thanks!

**Comment by davidmarkclements** [comment]
hey @bcomnes 

* there is now a test runner
* I'd accept a PR for this, as an opt-in behind a flag
* there is now built-in coverage reporting

closing, as I think that answers your questions :D

**Comment by bcomnes** [comment]
Awesome! Thank you for the info.

**Comment by bcomnes** [comment]
Re: default globbing to find tests:

Looks like this is the default regex for tap:

https://github.com/tapjs/node-tap/blob/60e2c67b2b9534d1423b03660fc3ab7954e9f4b6/bin/jack.js#L509

```js
'((\\/|^)(tests?|__tests?__)\\/.*|\\.(tests?|spec)|^\\/?tests?)\\.([mc]js|[jt]sx?)$',
```

But it also has some additional logic to prevent unproductive filewalking of large common folders:


```js
const defaultFiles = options => new Promise((res, rej) => {
  debug('try to get default files')
  const findit = require('findit')
  const good = strToRegExp(options['test-regex'])
  const bad = strToRegExp(options['test-ignore'])
  const fileFilter = f => {
    f = f.replace(/\\/g, '/')
    debug('fileFilter', f)
    const parts = f.split('/')
    const include = good.test(f) &&
      !bad.test(f) &&
      !parts.includes('node_modules') &&
      !parts.includes('tap-snapshots') &&
      !parts.includes('fixtures') &&
      !parts.includes('.git') &&
      !parts.includes('.hg') &&
      !parts.some(p => /^tap-testdir-/.test(p))
    debug('include?', f, include)
    return include
  }

  const addFile = files => f => fileFilter(f) && files.push(f)

  // search in any folder that isn't node_modules, .git, or tap generated
  // these can get pretty huge, so just walking them at all is costly
  const entryFilter =
    /^((node_modules|tap-snapshots|.git|.hg|fixtures)$|tap-testdir-)/
  fs.readdir(process.cwd(), (er, entries) => {
    debug('readdir cwd', er, entries)
    Promise.all(entries.filter(entry => !entryFilter.test(entry))
      .map(entry => new Promise((res, rej) => {
        fs.lstat(entry, (er, stat) => {
```

https://github.com/tapjs/node-tap/blob/6e04ce76207b003997da631b9243679bdcfde796/bin/run.js#L89-L120

If we do add a default glob (maybe hidden under a recursive flag?) I'm thinking a few ideas:

- Simplify the glob to be anything in a `tests` folder and also recursively look for *.test.[cm]js files.
  - (This would remove ts and jsx support since it dosn't look like its supported here. 
  - Drop's the *.spec.js alias, why have two names for the same thing?
  - Drop the __tests__ folder name pattern.  Get out of here python. 
- The recursive flag would rely on two options 
  - a file glob
  - an array of gitignore style ignore patterns.
